openapi: 3.1.0
info:
  title: Trello GPT Actions API
  version: 1.0.0

servers:
  - url: https://gpt-actions-trello.vercel.app

paths:
  /api/add-card:
    post:
      operationId: addCardToToday
      x-openai-isConsequential: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                desc:
                  type: string
                due:
                  type: string
                  format: date-time
                  description: "期限日時 (ISO 8601形式: YYYY-MM-DDTHH:mm:ssZ)"
              required:
                - name
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  cardId:
                    type: string
                  url:
                    type: string
  
  /api/get-cards:
    get:
      operationId: getTodayCards
      x-openai-isConsequential: false
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  cards:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        description:
                          type: string
                        due:
                          type: string
                          format: date-time
                        lastActivity:
                          type: string
                          format: date-time
                        url:
                          type: string
